### ISSUE TITLE
Bower components no se incluyen en el sitio compilado

### ISSUE THREAD

**Issue by alexishevia** [Startup-Panama/Site#1]
Cuando se compila el proyecto con `harp compile`, la carpeta con los bower components no se está incluyendo en el output directory. Tal vez haya una opción para incluir esta carpeta, no sé.

**Comment by molekilla** [comment]
hay que remover eso del .gitignore
https://github.com/Startup-Panama/Site/blob/master/.gitignore

**Comment by alexishevia** [comment]
Es la única manera? No me gusta tener que meter todos los bower_components a git. 

Lo ideal sería encontrar una manera de no tener que commit los bower_components a git, pero que sí se incluyan cuando uno compila el proyecto. Estaba revisando este issue https://github.com/sintaxi/harp/issues/305 pero parece que no hay una buena respuesta todavía.

Si no hay de otra lo hacemos como dice @molekilla .

**Comment by molekilla** [comment]
Que raro, y el bowerrc no tiene lo que buscas ?

**Comment by alexishevia** [comment]
Ya vi cuál es el issue. Harp está tratando de compilar los `bower_components`, pero falla con este error:

```
{
  "source": "Less",
  "dest": "CSS",
  "filename": "/Users/alexishevia/Projects/StartupPanama/bower_components/bootstrap/less/badges.less",
  "lineno": 11,
  "name": "NameError",
  "message": "variable @font-size-small is undefined",
```

Entonces aborta el compilado y no sigue copiando los demás archivos. (No sé cómo arreglarlo, pero voy a averiguar)

**Comment by alexishevia** [comment]
Al parecer varias personas han reportado el problema con bower_components cuando se trata de compilar harp (hay como 6 issues abiertos) pero los manes de harp dicen que pronto van a migrar a browserify, así que no quieren arreglar eso.

Decidí cargar los dependencies desde CDN en vez de usar bower.

**Comment by molekilla** [comment]
increible!

**Comment by Rolilink** [comment]
perfecto :)! +1

**Comment by Rolilink** [comment]
estaremos haciendo pair programming el fin yo y @alexishevia  para completar la logica @molekilla  asi que eso para el lunes tiene que estar listo :tada:

**Comment by molekilla** [comment]
Solidez ... debemos empujar a Sebastian para promo / evangelizacion.
Ustedes se han ido la milla extra por el esfuerzo
