### ISSUE TITLE
Hacer deployment

### ISSUE THREAD

**Issue by alexishevia** [Startup-Panama/Site#5]
Yo tengo un shared web host en webhostingbuzz.com que prácticamente no uso, podemos hospedarlo ahi.

Sólo habría que setear los DNS para que apunten allá y hacer deploy del código.

**Comment by molekilla** [comment]
Cuando ?

**Comment by Rolilink** [comment]
cuando quieras friend @alexishevia  creo que eso ya esta mas que listo!

**Comment by alexishevia** [comment]
Solo falta resolver los otros issues que están abiertos (son puras cosas pequeñas).

Ayer hablé con Sebastián, me dijo que le había pasado el documento a varias personas para recibir feedback. Hay que poner un deadline para ver hasta cuándo queremos esperar por feedback y si no hemos recibido nada lo publicamos así.

**Comment by molekilla** [comment]
Suena como burocracia...

**Comment by alexishevia** [comment]
Ok, la página ya está lista y deployed a mi server. Por ahora el index.html está vacío, pero pueden entrar a [http://panamastartupway.com/test.html](http://panamastartupway.com/test.html) para ver la página corriendo.

**Comment by alexishevia** [comment]
Voy a escribir un correo copiando a Sebastián y @aeperezt para que prueben y si todo está bien podemos hacer el launch del sitio cuando quieran.

**Comment by molekilla** [comment]
FB no me funciono, use github y si

**Comment by alexishevia** [comment]
@molekilla puedes abrir un issue nuevo con el mensaje de error (y screenshot preferiblemente) para ver si arreglamos eso?
