### ISSUE TITLE
Facebook sign in falla

### ISSUE THREAD

**Issue by molekilla** [Startup-Panama/Site#6]
![screenshot from 2015-01-30 21 52 29](https://cloud.githubusercontent.com/assets/1248071/5986548/652072c2-a8ca-11e4-9dc5-01f530402d93.png)

**Comment by Rolilink** [comment]
raro no he tocado nada en la configuración @alexishevia tu has tocado algo?

**Comment by alexishevia** [comment]
No, yo tampoco toqué nada. A mi me pasó que al principio no me quería funcionar el login de Facebook, por eso abrí el issue #3 . Después no sé qué pasó pero empezó a funcionar bien. Ahora a Rogelio no le funciona, pero no sé qué modificar, si me parece que los settings de Firebase están bien.

**Comment by aeperezt** [comment]
Esto me sale a mi cuando trato de entrar con facebook

**Comment by alexishevia** [comment]
Ok, encontré un setting que hacía falta y lo agregué. Creo que a @Rolilink y a mi no nos daba problema porque somos admins del app en facebook.

@molekilla @aeperezt pueden volver a probar?

**Comment by aeperezt** [comment]
el mismo problema.

**Comment by alexishevia** [comment]
OK... ahora sí debe funcionar. @molekilla @aeperezt Pueden probar otra vez?

**Comment by molekilla** [comment]
Works! C u a n d o sacamos este baby ? Estamos usando horas de AH y RL de
voluntarios. Si es democracia decidimos la mayoria y sacamos esto hoy.
Realmente no apoyo la causa de esperar a tuti y raimundi vea y opine sus 2
centavos.

**Comment by alexishevia** [comment]
Por mi está listo para salir hoy, creo que le hemos dado tiempo suficiente a todos para opinar.

**Comment by aeperezt** [comment]
Perfecto ya trabaja.

**Comment by aeperezt** [comment]
Jeje me recordó las reuniones de Go no Go.

Go.

**Comment by Rolilink** [comment]
Yo digo que en vez de reunirnos para ver como lanzamos esto, simplemente lo lancemos y nos reunamos después para ver como hacemos para hacerlo popular pero que empecemos lanzándolo.

**Comment by alexishevia** [comment]
Listo, la página ya está corriendo en http://panamastartupway.com/

**Comment by molekilla** [comment]
http://panamastartupway.com/ no -> http://panamastartupway.com/index.html

**Comment by alexishevia** [comment]
@molekilla cualquiera de las dos debe funcionar

**Comment by molekilla** [comment]
+10ⁿ
