### ISSUE TITLE
ver lista completa de firmantes

### ISSUE THREAD

**Issue by alexishevia** [Startup-Panama/Site#7]
Es posible que se vea mas larga la lista de firmantes? Es decir ahora solo muestra los primeros 6..podria ser algo como los plugins de facebook que te permiten scroll down todos los miembros?

**Comment by Rolilink** [comment]
se podría crear una vista y un collection especial que filtre mas miembros al final de la pagina o se crea una vista con paginación que muestre todas las firmas.

**Comment by alexishevia** [comment]
Yo estaba pensando hacer que el "y N personas más" sea un link. Cuando das click, abre un modal con la lista completa. No sé qué te parece?

**Comment by aeperezt** [comment]
eso me parece mejor

**Comment by Rolilink** [comment]
100% con @alexishevia  esa es mejor idea!
